### ISSUE TITLE
CSP Error while running a scan

### ISSUE THREAD

**Issue by cadecairos** [mozilla/http-observatory-website#112]
When running a scan of a site, the final scan is failing to load for me due to a CSP error in console.

I've hit the bug in Firefox and Chrome. Edge didn't seem affected.

Here's the error:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://observatory.mozilla.org”). Source: call to eval() or related function blocked by CSP.

  httpobs-third-party.FIA9KMCIIHehg6_s7Q7YmEKBHUPw9avLceRNLfalSio=.js:517
```

Here's the url: I hit it with: https://observatory.mozilla.org/analyze.html?host=indicators.internethealthreport.org

**Comment by april** [comment]
I don't get that eval() error -- I don't use eval at all.  That said, what I'm noticing is that the Observatory gets stuck attempting to scan that site forever and ever until it gives up.  It's very strange!

**Comment by april** [comment]
Oh, I see the problem.  The site has an invalid certificate chain, and its one of those weird ones that causes exceptions in the exception handler, and it's something that I can't seem to catch.

What is happening is that your site isn't sending a complete certificate chain and that's causing HTTPS to fail.  Browsers are extraordinarily good about working around this, because they cache zillions of intermediate certificates, but a lot of libraries have trouble filling in the chain.  If you look at ssllabs.com, you'll see that it's setup correctly in this regards:

https://www.ssllabs.com/ssltest/analyze.html?d=indicators.internethealthreport.org

Once you fix the missing broken chain, I think things should work themselves out.  Let me know if that fixes things!

**Comment by april** [comment]
Here is the full Python stack trace, if helpful:

```python
 ❯ python3                                                                                                   [11:13:28]
Python 3.6.1 (default, Apr 14 2017, 23:28:33)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://indicators.internethealthreport.org')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
```

**Comment by cadecairos** [comment]
Oh cool, thanks for digging in and finding that issue. I'll let the vendor know that the certificate chain isn't installed.

**Comment by april** [comment]
I think I've fixed these certificate chain problems. Do you still have issues?

**Comment by cadecairos** [comment]
I haven't since the first report - I think it's safe to close this issue now. Thanks @april!

**Comment by april** [comment]
Thanks much!
