### ISSUE TITLE
error: site down after adding csp and secure cookie into header

### ISSUE THREAD

**Issue by tchncs** [mozilla/http-observatory-website#79]
Hi there, 

after adding the following into my sites header, the observatory fails to finish the check:

```
# csp from mozilla docs
"Content-Security-Policy: default-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none'"
"Set-Cookie ^(.*)$ $1;HttpOnly;Secure"
```

**Comment by marumari** [comment]
Can you send me the site so I can take a look at it?  There is nothing about this particular policy that I would think that would cause an error.

**Comment by tchncs** [comment]
Hi, https://illuna-minetest.tk for example.

**Comment by marumari** [comment]
Are you sure the header is the issue?  I think your site is returning an invalid HTTP response, but clients are working around it.  Here is what happens when I make a request with requests:

```python
>>> import requests
>>> requests.get('https://illuna-minetest.tk')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 262, in _decode
    data = self._decoder.decompress(data)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 62, in decompress
    return self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 703, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 404, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 267, in _decode
    "failed to decode it." % content_encoding, e)
requests.packages.urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 641, in send
    r.content
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 781, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 708, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))
```

**Comment by floatingatoll** [comment]
Specifically, the broken header is here:

< Set-Cookie: educator_locale=en; path=/; expires=Sun, 28 Dec 2036 19:21:04
-0000
< Set-Cookie ^(.*)$ $1;HttpOnly;Secure:

**Comment by marumari** [comment]
I suspect you may have:

```
Header set Set-Cookie ^(.*)$ $1;HttpOnly;Secure
```

When you meant to have:

```
Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
```

Where did you see this in the Mozilla docs, and can I see your configuration line?

**Comment by tchncs** [comment]
Hmm i may need to check the Caddy documentation / ask in their forums then.
I guess(!) i cannot change the `set` to `edit` / i don't know how yet.


```
        header / {
                Strict-Transport-Security "max-age=31536000;"
                X-XSS-Protection "1; mode=block"
                X-Content-Type-Options "nosniff"
                #X-Frame-Options "DENY"
                "Content-Security-Policy: default-src https: 'unsafe-eval' 'unsafe-inline'"
                "Set-Cookie ^(.*)$ $1;HttpOnly;Secure"
        }
```

The cookie headeroption is not from the mozilla docs.

**Comment by marumari** [comment]
Yeah, I agree, I don't know where it came from.  The option you have there would only work in something like Apache, I have no idea and I would be surprised if it worked in Caddy.

**Comment by marumari** [comment]
I'm going to close this, because I don't think the issue is with the Observatory and even if we wanted to work around it, I don't think we would ever write our own header parser to work around invalid HTTP responses.  :)
